
package net.ch72.samples.wssample.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sample", targetNamespace = "http://wssample.samples.ch72.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sample {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://wssample.samples.ch72.net/", className = "net.ch72.samples.wssample.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://wssample.samples.ch72.net/", className = "net.ch72.samples.wssample.client.SayHelloResponse")
    @Action(input = "http://wssample.samples.ch72.net/Sample/sayHelloRequest", output = "http://wssample.samples.ch72.net/Sample/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
